basePath: /api/v1
definitions:
  main.ScanListItem:
    properties:
      comments:
        type: string
      created:
        type: string
      grade:
        type: string
      id:
        type: string
      score:
        type: integer
      status:
        type: string
      target:
        type: string
    type: object
  main.ScanListResponse:
    properties:
      scans:
        items:
          $ref: '#/definitions/main.ScanListItem'
        type: array
      total:
        type: integer
    type: object
  main.ScanRequest:
    description: Request body for submitting a new TLS/SSL scan
    properties:
      check_sslv3:
        description: |-
          Enable deep scan with SSL v3 detection using raw sockets
          @example false
        example: false
        type: boolean
      comments:
        description: |-
          Optional comments for tracking (max 100 chars)
          @example "Ticket #12345"
        example: Quarterly security audit
        maxLength: 100
        type: string
      priority:
        description: |-
          Scan priority (1-10, higher = more priority)
          @example 5
        example: 5
        type: integer
      target:
        description: |-
          Target hostname or IP address to scan (required)
          @example example.com or 192.168.1.1:8443
        example: example.com
        type: string
    required:
    - target
    type: object
  main.ScanResponse:
    properties:
      created:
        type: string
      id:
        type: string
      message:
        type: string
      queue_position:
        type: integer
      status:
        type: string
    type: object
  main.ScanResultResponse:
    properties:
      certificate_days_remaining:
        type: integer
      certificate_expires_at:
        type: string
      certificate_grade:
        type: string
      certificate_issuer:
        type: string
      certificate_key_size:
        type: integer
      certificate_key_type:
        type: string
      certificate_score:
        type: integer
      cipher_strength_score:
        type: integer
      comments:
        type: string
      connection_type:
        type: string
      grade:
        type: string
      grade_degradations:
        items:
          additionalProperties: true
          type: object
        type: array
      id:
        type: string
      key_exchange_score:
        type: integer
      protocol_grade:
        type: string
      protocol_score:
        type: integer
      protocol_support_score:
        type: integer
      result:
        type: object
      score:
        type: integer
      service_type:
        type: string
      status:
        type: string
      vulnerabilities:
        items:
          additionalProperties: true
          type: object
        type: array
      weak_ciphers:
        items:
          additionalProperties: true
          type: object
        type: array
      weak_protocols:
        items:
          additionalProperties: true
          type: object
        type: array
    type: object
host: localhost:8000
info:
  contact: {}
  description: Request body for submitting a new TLS/SSL scan
  title: TLS Scanner Portal API
  version: 1.2.0
paths:
  /health:
    get:
      consumes:
      - application/json
      description: Check if the API and its dependencies are healthy
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "503":
          description: Service Unavailable
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Health check
      tags:
      - health
  /scans:
    get:
      consumes:
      - application/json
      description: Get a list of all scans with their status and grades
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.ScanListResponse'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: List all scans
      tags:
      - scans
    post:
      consumes:
      - application/json
      description: Submit a single target or multiple targets for TLS/SSL scanning
      parameters:
      - description: Single scan target
        in: body
        name: scan
        schema:
          $ref: '#/definitions/main.ScanRequest'
      - description: Batch of scan targets (up to 100)
        in: body
        name: batch
        schema:
          items:
            $ref: '#/definitions/main.ScanRequest'
          type: array
      produces:
      - application/json
      responses:
        "202":
          description: Batch scan response
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Submit a new scan or batch of scans
      tags:
      - scans
  /scans/{id}:
    get:
      consumes:
      - application/json
      description: Retrieve the result of a specific scan by its ID
      parameters:
      - description: Scan ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.ScanResultResponse'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get scan result
      tags:
      - scans
  /stats:
    get:
      consumes:
      - application/json
      description: Get scan statistics including total scans, queue length, etc.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Get statistics
      tags:
      - stats
schemes:
- http
- https
swagger: "2.0"
